CREATE DATABASE global_bi;
USE global_bi;

WITH RECURSIVE seq AS (
  SELECT 1 AS n
  UNION ALL
  SELECT n+1 FROM seq WHERE n < 100000
)
SELECT * FROM seq;

CREATE TABLE dim_date (
  date_id INT PRIMARY KEY,
  full_date DATE,
  year INT,
  month INT,
  day INT,
  quarter VARCHAR(2)
);

INSERT INTO dim_date
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 DATE_ADD('2010-01-01', INTERVAL n DAY),
 YEAR(DATE_ADD('2010-01-01', INTERVAL n DAY)),
 MONTH(DATE_ADD('2010-01-01', INTERVAL n DAY)),
 DAY(DATE_ADD('2010-01-01', INTERVAL n DAY)),
 CONCAT('Q', QUARTER(DATE_ADD('2010-01-01', INTERVAL n DAY)))
FROM seq;

SET SESSION cte_max_recursion_depth = 100000;

CREATE TABLE numbers (n INT PRIMARY KEY);
INSERT INTO numbers (n)
SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + e.N*10000 + 1
FROM 
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d,
(SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
LIMIT 100000;


CREATE TABLE dim_product (
  product_id INT PRIMARY KEY,
  product_name VARCHAR(100),
  category VARCHAR(50),
  price DECIMAL(10,2)
);

INSERT INTO dim_product
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 CONCAT('Product-', n),
 ELT(1+MOD(n,5),'Electronics','Clothing','Grocery','Furniture','Sports'),
 ROUND(50 + (RAND()*950),2)
FROM seq;

CREATE TABLE dim_customer (
  customer_id INT PRIMARY KEY,
  customer_name VARCHAR(100),
  country VARCHAR(50),
  segment VARCHAR(50)
);

INSERT INTO dim_customer
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 CONCAT('Customer-', n),
 ELT(1+MOD(n,5),'India','USA','UK','Canada','Germany'),
 ELT(1+MOD(n,3),'Retail','Corporate','Home Office')
FROM seq;

CREATE TABLE dim_store (
  store_id INT PRIMARY KEY,
  store_name VARCHAR(100),
  region VARCHAR(50)
);

INSERT INTO dim_store
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 CONCAT('Store-', n),
 ELT(1+MOD(n,4),'North','South','East','West')
FROM seq;

CREATE TABLE fact_sales (
  sales_id INT PRIMARY KEY,
  date_id INT,
  product_id INT,
  customer_id INT,
  store_id INT,
  quantity INT,
  sales_amount DECIMAL(12,2),
  profit DECIMAL(12,2)
);

INSERT INTO fact_sales
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 1 + MOD(n,100000),
 1 + MOD(n,100000),
 1 + MOD(n,100000),
 1 + MOD(n,100000),
 1 + MOD(n,10),
 ROUND(100 + (RAND()*900),2),
 ROUND(20 + (RAND()*300),2)
FROM seq;

CREATE TABLE fact_inventory (
  inventory_id INT PRIMARY KEY,
  product_id INT,
  store_id INT,
  stock_qty INT,
  reorder_level INT
);

INSERT INTO fact_inventory
WITH RECURSIVE seq AS (
  SELECT 1 n
  UNION ALL SELECT n+1 FROM seq WHERE n < 100000
)
SELECT 
 n,
 1 + MOD(n,100000),
 1 + MOD(n,100000),
 50 + MOD(n,200),
 20 + MOD(n,50)
FROM seq;

